name: Build and Release

on:
  push:
    tags:
      - 'v*' # This will trigger the workflow when you push a tag starting with 'v'
  workflow_dispatch: # This allows manual triggering from the GitHub UI

permissions:
  contents: write # This is needed to create releases

jobs:
  build:
    runs-on: windows-latest # Using Windows since your tool uses Windows-specific features
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build executable
      run: |
        pyinstaller --onefile --icon=resources/logoico.ico --name="TARS-Utilities" tarsutilitiestool.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: TARS-Utilities
        path: dist/TARS-Utilities.exe
        
    - name: Create Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/TARS-Utilities.exe
        body: |
          # TARS Utilities Tool Release
          
          Automated build of the latest version
          
          ## Installation
          - Download the .exe file
          - Run as administrator (required for shutdown functionality)
          - yay, that's it!
        draft: false
        prerelease: false